version: "3"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map container's port 5173 to host's port 4173 (preview port)
      - "4173:5173"
    volumes:
      - ./docs-new:/docs/docs-new
      - ./.vitepress:/docs/.vitepress
      - ./package.json:/docs/package.json
      - ./package-lock.json:/docs/package-lock.json
    environment:
      - NODE_ENV=development
    command: npm run docs:dev -- --host 0.0.0.0
