version: "3"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/docs
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY:-}
    command: mkdocs serve --dev-addr=0.0.0.0:8000 --watch-theme
